# Server 配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
  # 配置请求头
  max-http-header-size: 4MB
  # 开启优雅停机，默认immediate是立即关机
  shutdown: graceful

# Spring 配置
spring:
  # 激活的配置文件
  profiles:
    active: dev
  # 优雅停机的需求
  lifecycle:
    timeout-per-shutdown-phase: 60s # 设置缓冲期，最大等待时间
  # 医用名称
  application:
    name: spring-boot-rabbitmq
  # Jackson 的日期格式信息
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true