server:
  port: 9000

spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.9.64

management:
  endpoints:
    web:
      exposure:
        include: "*"


## 日志的配置
logging:
  level:
    ROOT: DEBUG
    org.thymeleaf.TemplateEngine: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org.springframework.core.env.PropertySourcesPropertyResolver: INFO
    org.springframework.beans.factory.support.DefaultListableBeanFactory: INFO
    me.kany.project.learning: DEBUG
    me.kany.project.learning.mapper: INFO
  pattern:
    console: ${CONSOLE_LOG_PATTERN:【%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint}】 %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
    file: 【%d{yyyy-MM-dd HH:mm:ss.SSS}】 %-5level [%thread] --- %logger --- %msg%n
  file:
    path: logs/
  logback:
    rollingpolicy:
      max-history: 20
      max-file-size: 20MB