#!/bin/bash

#echo "Checking java JDK version"
#command -v javac >/dev/null 2>&1 || { echo >&2 "Java JDK is not installed"; }
#variables
purge_='sudo apt-get purge '
update_='sudo apt update '
install_='sudo apt install '

#checking for java files and exe
echo Java JRE -
if type -p java; then
  echo Found Java executable in PATH
  _java=java
elif [[ -n $JAVA_HOME ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
  echo Found Java executable in JAVA_HOME
  _java="$JAVA_HOME/bin/java"
else
  echo "no JRE found"
fi

if [[ "$_java" ]]; then
  version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
  echo Version "$version"
fi

echo
echo Java JDK -
if type -p javac; then
  echo Found Javac executable in PATH
  _javac=javac
elif [[ -n $JAVA_HOME ]] && [[ -x "$JAVA_HOME/bin/javac" ]]; then
  echo Found Javac executable in JAVA_HOME
  _javac="$JAVA_HOME/bin/javac"
else
  echo "no JDK found"
  echo "Previous Java JDK files will also be removed in installation."
  read -r -p "Do you want to install it now? [y/N] " response
  if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    echo "Installing Java JDK "
    $purge_ 'java openjdk-*'
    $update_
    $install_ java -y
  else
    echo "Installation aborted !"
    exit
  fi
fi

if [[ "$_javac" ]]; then
  version=$("$_javac" -version 2>&1 | awk '{print $2}')
  echo Version "$version"
fi
#javac -version 2>&1 | head -n 1
#end of java
