#!/bin/bash

#checking for java files and exe
echo Java JRE -
if type -p java; then
  echo Found Java executable in PATH
  _java=java
elif [[ -n $JAVA_HOME ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
  echo Found Java executable in JAVA_HOME
  _java="$JAVA_HOME/bin/java"
else
  echo "no JRE found"
fi

if [[ "$_java" ]]; then
  version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
  echo Version "$version"
fi
