server:
  port: 1174

spring:
  application:
    name: spring-native-ipfs-server
  aop:
    auto: true
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

ipfs:
  node: /ip4/192.168.9.124/tcp/5001
  url: http://192.168.9.124:8080/ipfs/


logging:
  level:
    ROOT: DEBUG
    org.thymeleaf.TemplateEngine: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org.springframework.core.env.PropertySourcesPropertyResolver: INFO
    org.springframework.beans.factory.support.DefaultListableBeanFactory: INFO
    me.kany.project.learning: DEBUG
    me.kany.project.learning.mapper: INFO
  pattern:
    console: ${CONSOLE_LOG_PATTERN:[%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint}] %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
